### ISSUE TITLE
Inclusion of Kotlin Codes.

### ISSUE THREAD

**Issue by justneutral1** [pokkst/bitcoincashj#12]
Thumbs up to you guys. I love what you're doing. Please I'm having issues using the library due to the inclusion of Kotlin class SlTxBuilder in particular. 
I wish to plead for you to help change the class to Java class. 
If that won't be possible I would appreciate any form of assistance on integrating the code.
Thank you in advance.

**Comment by pokkst** [comment]
Install Kotlin.
